### ISSUE TITLE
About Memrise API question

### ISSUE THREAD

**Issue by josephquang97** [ollipa/memrise-audio-uploader#2]
Hello there,

Firstly, I thank you for your project, I think it's really useful. And I have learnt about lot from your project as the way you use `pydantic`, `lxml`. I could say that I never know that existing if I don't look at your codes. I start to learn these libraries they're awesome. I would like to use some structures of you codes to make my own library due to your library dropped support Python Version 3.7.

That's what I can learn from watching at your codes. Some things else I would like to know, however I couldn't understand if only watch your code. Could you please help me know how to you figure out the URL keys?
For examples:
In my cases, I want to get more information about the course which you're not the author.
`https://app.memrise.com/v1.17/courses/<course_id>/`
I saw that the course have 2 levels, and then I guess the next path maybe `levels`, so I try with the following
`https://app.memrise.com/v1.17/courses/<course_id>/levels/`
It works for me. But, I only saw the learnable_id in the levels. I would like to know the text of these learnable_ids. I couldn't guess correctly the path which I need.

Could you please help me?
Thank you in advance.

**Comment by ollipa** [comment]
@josephquang97, sorry for my terribly late answer. Hopefully you already solved your issue. Unfortunately, I can't help much with the Memrise API. Memrise doesn't provide any API documentation so you will have to reverse engineer the API. One way to do this is to open Memrise website and inspect the network activity with your browser. For example with Chrome dev tools:
https://developer.chrome.com/docs/devtools/network/
